function getGraph() {
	var graph = Viva.Graph.graph();

	graph.addNode( 1 , { name: '김용길', url: 'images/MD.png' });
	graph.addNode( 2 , { name: '김창윤', url: 'images/MD.png' });
	graph.addNode( 3 , { name: '김창순', url: 'images/MD.png' });
	graph.addNode( 4 , { name: '김계윤', url: 'images/4.png' });
	graph.addNode( 5 , { name: '김영순', url: 'images/5.png' });
	graph.addNode( 6 , { name: '김영옥', url: 'images/6.png' });
	graph.addNode( 7 , { name: '김영일', url: 'images/7.png' });
	graph.addNode( 8 , { name: '김영관', url: 'images/8.png' });
	graph.addNode( 9 , { name: '김영숙', url: 'images/FA.png' });
	graph.addNode( 10 , { name: '김정숙', url: 'images/FA.png' });
	graph.addNode( 11 , { name: '김종숙', url: 'images/FA.png' });
	graph.addNode( 12 , { name: '김태웅', url: 'images/12.png' });
	graph.addNode( 13 , { name: '김태미', url: 'images/FA.png' });
	graph.addNode( 14 , { name: '김태희', url: 'images/FA.png' });
	graph.addNode( 15 , { name: '김동준', url: 'images/15.png' });
	graph.addNode( 16 , { name: '김동건', url: 'images/16.png' });
	graph.addNode( 17 , { name: '김태경', url: 'images/FA.png' });
	graph.addNode( 18 , { name: '김태성', url: 'images/MA.png' });
	graph.addNode( 19 , { name: '김태종', url: 'images/MA.png' });
	graph.addNode( 20 , { name: '김진영', url: 'images/FA.png' });
	graph.addNode( 21 , { name: '김태훈', url: 'images/21.png' });
	graph.addNode( 22 , { name: '김태형', url: 'images/22.png' });
	graph.addNode( 23 , { name: '김태준', url: 'images/23.png' });
	graph.addNode( 24 , { name: '김태욱', url: 'images/24.png' });
	graph.addNode( 25 , { name: '김영민', url: 'images/MA.png' });
	graph.addNode( 26 , { name: '김영호', url: 'images/26.png' });
	graph.addNode( 27 , { name: '김영철', url: 'images/27.png' });
	graph.addNode( 28 , { name: '김인숙', url: 'images/FA.png' });
	graph.addNode( 29 , { name: '김희숙', url: 'images/FA.png' });
	graph.addNode( 30 , { name: '김기웅', url: 'images/MA.png' });
	graph.addNode( 31 , { name: '김재연', url: 'images/MA.png' });
	graph.addNode( 32 , { name: '김도훈', url: 'images/32.png' });
	graph.addNode( 33 , { name: '김신정', url: 'images/FA.png' });
	graph.addNode( 34 , { name: '김준성', url: 'images/MA.png' });
	graph.addNode( 35 , { name: '김대영', url: 'images/MA.png' });
	graph.addNode( 36 , { name: '김미양', url: 'images/FA.png' });
	graph.addNode( 37 , { name: '김대익', url: 'images/MA.png' });
	graph.addNode( 38 , { name: '김준석', url: 'images/38.png' });
	graph.addNode( 39 , { name: '김도연', url: 'images/39.png' });
	graph.addNode( 40 , { name: '김건우', url: 'images/40.png' });
	graph.addNode( 41 , { name: '김강민', url: 'images/41.png' });
	graph.addNode( 42 , { name: '김창헌', url: 'images/42.png' });
	graph.addNode( 43 , { name: '김나윤', url: 'images/FA.png' });
	graph.addNode( 44 , { name: '김하린', url: 'images/MA.png' });
	graph.addNode( 45 , { name: '김양금', url: 'images/FD.png' });
	graph.addNode( 46 , { name: '김양연', url: 'images/FD.png' });
	graph.addNode( 47 , { name: '김양희', url: 'images/FD.png' });
	graph.addNode( 48 , { name: '김경숙', url: 'images/FA.png' });
	graph.addNode( 49 , { name: '김명숙', url: 'images/FA.png' });
	graph.addNode( 50 , { name: '김화윤', url: 'images/MD.png' });
	graph.addNode( 51 , { name: '김영준', url: 'images/MD.png' });
	graph.addNode( 52 , { name: '김영부', url: 'images/MD.png' });
	graph.addNode( 53 , { name: '김영운', url: 'images/MD.png' });
	graph.addNode( 54 , { name: '김영찬', url: 'images/MA.png' });
	graph.addNode( 55 , { name: '김영', url: 'images/55.png' });
	graph.addNode( 56 , { name: '김선영', url: 'images/FA.png' });
	graph.addNode( 57 , { name: '김봉석', url: 'images/MA.png' });
	graph.addNode( 58 , { name: '김경석', url: 'images/MA.png' });
	graph.addNode( 59 , { name: '김미경', url: 'images/FA.png' });
	graph.addNode( 60 , { name: '김미애', url: 'images/FA.png' });
	graph.addNode( 61 , { name: '김명석', url: 'images/MA.png' });
	graph.addNode( 62 , { name: '김현석', url: 'images/MA.png' });
	graph.addNode( 63 , { name: '김도경', url: 'images/MA.png' });
	graph.addNode( 64 , { name: '김나희', url: 'images/FA.png' });
	graph.addNode( 65 , { name: '김치호', url: 'images/MA.png' });
	graph.addNode( 66 , { name: '김우정', url: 'images/FA.png' });
	graph.addNode( 67 , { name: '김지훈', url: 'images/MA.png' });
	graph.addNode( 68 , { name: '김지수', url: 'images/MA.png' });
	graph.addNode( 69 , { name: '김하진', url: 'images/MA.png' });
	graph.addNode( 70 , { name: '김해림', url: 'images/FA.png' });
	graph.addNode( 71 , { name: '김동건', url: 'images/MA.png' });
	graph.addNode( 72 , { name: '김수현', url: 'images/FA.png' });
	graph.addNode( 73 , { name: '김수진', url: 'images/FA.png' });
	graph.addNode( 74 , { name: '김남희', url: 'images/FA.png' });
	graph.addLink( 1 , 2 , { id:  1 , type: 'child' });
	graph.addLink( 1 , 3 , { id:  2 , type: 'child' });
	graph.addLink( 1 , 4 , { id:  3 , type: 'child' });
	graph.addLink( 2 , 5 , { id:  4 , type: 'child' });
	graph.addLink( 2 , 6 , { id:  5 , type: 'child' });
	graph.addLink( 2 , 7 , { id:  6 , type: 'child' });
	graph.addLink( 2 , 8 , { id:  7 , type: 'child' });
	graph.addLink( 2 , 9 , { id:  8 , type: 'child' });
	graph.addLink( 2 , 10 , { id:  9 , type: 'child' });
	graph.addLink( 2 , 11 , { id:  10 , type: 'child' });
	graph.addLink( 5 , 12 , { id:  11 , type: 'child' });
	graph.addLink( 5 , 13 , { id:  12 , type: 'child' });
	graph.addLink( 5 , 14 , { id:  13 , type: 'child' });
	graph.addLink( 12 , 15 , { id:  14 , type: 'child' });
	graph.addLink( 12 , 16 , { id:  15 , type: 'child' });
	graph.addLink( 6 , 17 , { id:  16 , type: 'child' });
	graph.addLink( 6 , 18 , { id:  17 , type: 'child' });
	graph.addLink( 6 , 19 , { id:  18 , type: 'child' });
	graph.addLink( 7 , 20 , { id:  19 , type: 'child' });
	graph.addLink( 7 , 21 , { id:  20 , type: 'child' });
	graph.addLink( 8 , 22 , { id:  21 , type: 'child' });
	graph.addLink( 8 , 23 , { id:  22 , type: 'child' });
	graph.addLink( 8 , 24 , { id:  23 , type: 'child' });
	graph.addLink( 3 , 25 , { id:  24 , type: 'child' });
	graph.addLink( 3 , 26 , { id:  25 , type: 'child' });
	graph.addLink( 3 , 27 , { id:  26 , type: 'child' });
	graph.addLink( 3 , 28 , { id:  27 , type: 'child' });
	graph.addLink( 3 , 29 , { id:  28 , type: 'child' });
	graph.addLink( 4 , 35 , { id:  29 , type: 'child' });
	graph.addLink( 4 , 36 , { id:  30 , type: 'child' });
	graph.addLink( 4 , 37 , { id:  31 , type: 'child' });
	graph.addLink( 25 , 30 , { id:  32 , type: 'child' });
	graph.addLink( 25 , 31 , { id:  33 , type: 'child' });
	graph.addLink( 26 , 32 , { id:  34 , type: 'child' });
	graph.addLink( 27 , 33 , { id:  35 , type: 'child' });
	graph.addLink( 27 , 34 , { id:  36 , type: 'child' });
	graph.addLink( 35 , 38 , { id:  37 , type: 'child' });
	graph.addLink( 35 , 39 , { id:  38 , type: 'child' });
	graph.addLink( 35 , 40 , { id:  39 , type: 'child' });
	graph.addLink( 35 , 41 , { id:  40 , type: 'child' });
	graph.addLink( 37 , 42 , { id:  41 , type: 'child' });
	graph.addLink( 18 , 43 , { id:  42 , type: 'child' });
	graph.addLink( 19 , 44 , { id:  43 , type: 'child' });
	graph.addLink( 1 , 45 , { id:  44 , type: 'child' });
	graph.addLink( 1 , 46 , { id:  45 , type: 'child' });
	graph.addLink( 1 , 47 , { id:  46 , type: 'child' });
	graph.addLink( 1 , 50 , { id:  47 , type: 'child' });
	graph.addLink( 2 , 48 , { id:  48 , type: 'child' });
	graph.addLink( 2 , 49 , { id:  49 , type: 'child' });
	graph.addLink( 50 , 51 , { id:  50 , type: 'child' });
	graph.addLink( 50 , 52 , { id:  51 , type: 'child' });
	graph.addLink( 50 , 53 , { id:  52 , type: 'child' });
	graph.addLink( 50 , 54 , { id:  53 , type: 'child' });
	graph.addLink( 50 , 55 , { id:  54 , type: 'child' });
	graph.addLink( 50 , 56 , { id:  55 , type: 'child' });
	graph.addLink( 51 , 57 , { id:  56 , type: 'child' });
	graph.addLink( 51 , 58 , { id:  57 , type: 'child' });
	graph.addLink( 51 , 59 , { id:  58 , type: 'child' });
	graph.addLink( 51 , 60 , { id:  59 , type: 'child' });
	graph.addLink( 52 , 61 , { id:  60 , type: 'child' });
	graph.addLink( 52 , 62 , { id:  61 , type: 'child' });
	graph.addLink( 54 , 63 , { id:  62 , type: 'child' });
	graph.addLink( 54 , 64 , { id:  63 , type: 'child' });
	graph.addLink( 55 , 65 , { id:  64 , type: 'child' });
	graph.addLink( 55 , 66 , { id:  65 , type: 'child' });
	graph.addLink( 57 , 67 , { id:  66 , type: 'child' });
	graph.addLink( 57 , 68 , { id:  67 , type: 'child' });
	graph.addLink( 58 , 69 , { id:  68 , type: 'child' });
	graph.addLink( 58 , 70 , { id:  69 , type: 'child' });
	graph.addLink( 61 , 71 , { id:  70 , type: 'child' });
	graph.addLink( 61 , 72 , { id:  71 , type: 'child' });
	graph.addLink( 62 , 73 , { id:  72 , type: 'child' });
	graph.addLink( 62 , 74 , { id:  73 , type: 'child' });
	return graph;
}
